# Nombre del workflow que aparecerá en la pestaña "Actions"
name: Python CI
 

 # Trigger: define cuándo se ejecuta la pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:  # Inicio de los jobs, que son agrupaciones de tareas
  build:  # Nombre del job
  #Set up job
    runs-on: ubuntu-latest  # Runner: sistema operativo en el que se ejecutará (Ubuntu)


    steps:
    - name: Clonar el código
      uses: actions/checkout@v3  #pipeline va a descargar el código de tu repositorio en la máquina virtual


# Segundo paso: instala y configura Python
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

# Tercer paso: instala las dependencias del proyecto
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

# Cuarto paso: ejecuta las pruebas automatizadas
    - name: Ejecutar pruebas
      run: |
        pytest
